#!/usr/bin/python3
# This Python file uses the following encoding: utf-8

import os
import sys
import errno
from stat import S_IREAD, S_IWRITE, S_IRGRP, S_IROTH
import hashlib

def hashFor(data):
    hashId = hashlib.md5()
    hashId.update(repr(data).encode('utf-8'))
    return hashId.hexdigest()

if (len(sys.argv) < 2):
    print('Usage: qmlcombiner.py <main qml file> <output>')
    exit(1)

output_file = sys.argv[2]
if not os.path.exists(os.path.dirname(output_file)):
    try:
        os.makedirs(os.path.dirname(output_file))
        print('Creating directory ' + os.path.dirname(output_file))
    except OSError as exc:
        if exc.errno != errno.EEXIST:
            raise

handle = open(sys.argv[1], "r")
data = handle.readlines()
operator = "//include:"
operator_remove = "//[remove]"
output = []
for line in data:
    if operator in line:
        split = line.split(" ")
        incf = split[len(split)-1].replace('\n', '')
        _spaces = 0
        for symbol in line:
            if symbol == ' ':
                _spaces += 1
        spaces = ' ' * (_spaces - 1)
        print('Found include file: ' + incf)
        include = open(os.path.join(os.path.dirname(sys.argv[1]), incf), "r")
        proceed = []
        for _line in include:
            if _line[:12] == "/*[remove]*/":
                continue
            if _line[:6] != "import":
                proceed.append(spaces + _line)
        include.close()
        output.append(spaces + "// included from " + incf + "\n")
        for __line in proceed:
            output.append(__line)
        output.append(spaces + "// end of file " + incf + "\n")
    else:
        output.append(line)
handle.close()

output.insert(0, "// Do not edit by hand!\n")
output.insert(0, "// This file was generated by qmlcombiner.py\n")

print('Generating ' + output_file)

if os.path.isfile(output_file):
    handle = open(output_file, "r")
    data = handle.readlines()
    handle.close()
    hex1 = hashFor(data)
    hex2 = hashFor(output)
    if (hex1 == hex2):
        print('No need to generate.')
        exit(0)
    os.chmod(output_file, S_IREAD|S_IWRITE|S_IRGRP|S_IROTH)

handle = open(output_file, "w+")

for line in output:
    handle.write(line)
handle.close()
os.chmod(output_file, S_IREAD|S_IRGRP|S_IROTH)
